# Generated by Django 4.2 on 2024-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.CharField(default='ED5A6AC', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
