# Generated by Django 4.2 on 2024-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.CharField(default='F62C785', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
