# Generated by Django 4.2 on 2024-04-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.CharField(default='D43CA63', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='family_id',
            field=models.ForeignKey(db_column='family_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to='authentication.family'),
        ),
    ]
