# Generated by Django 5.0.4 on 2024-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_family_id_alter_user_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.CharField(default='99E6B4B', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
