# Generated by Django 4.2 on 2024-05-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_family_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.CharField(default='039224A', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
