# Generated by Django 4.2 on 2024-04-16 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_family_id_alter_user_family_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('create_date', models.TimeField(auto_now_add=True)),
                ('update_date', models.TimeField(auto_now=True)),
                ('keyword', models.CharField(blank=True, max_length=16)),
                ('emotion', models.IntegerField(null=True)),
                ('family_id', models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='authentication.family')),
            ],
            options={
                'verbose_name': 'posts',
                'verbose_name_plural': 'post',
                'ordering': ('id',),
            },
        ),
    ]
