# Generated by Django 4.2 on 2024-04-16 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 8, 21, 22, 389195, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 8, 21, 22, 391133, tzinfo=datetime.timezone.utc)),
        ),
    ]
