# Generated by Django 4.2 on 2024-04-17 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_alter_post_date_alter_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 17, 9, 6, 52, 403490, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 17, 9, 6, 52, 405113, tzinfo=datetime.timezone.utc)),
        ),
    ]
