# Generated by Django 4.2 on 2024-04-19 04:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_report_post_count_alter_post_date_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 4, 46, 31, 153567, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 19, 4, 46, 31, 153567, tzinfo=datetime.timezone.utc)),
        ),
    ]
