# Generated by Django 4.2 on 2024-05-01 04:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_family_id'),
        ('conversation', '0006_alter_post_date_alter_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_rate', models.FloatField(default=0)),
                ('bad_rate', models.FloatField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('emotion_1', models.IntegerField(default=0)),
                ('emotion_2', models.IntegerField(default=0)),
                ('emotion_3', models.IntegerField(default=0)),
                ('emotion_4', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 1, 4, 32, 12, 447999, tzinfo=datetime.timezone.utc))),
                ('keywords', models.TextField(default='')),
                ('family_id', models.ForeignKey(db_column='family_id', on_delete=django.db.models.deletion.CASCADE, related_name='day', to='authentication.family')),
            ],
            options={
                'verbose_name': 'reports',
                'verbose_name_plural': 'report',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 1, 4, 32, 12, 447999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
